import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

export default function AppealsScreen() { const colors = useColors(); const router = useRouter(); const appeals = trpc.appeals.mine.useQuery(); return <ScreenContainer className="bg-background" edges={["top", "bottom", "left", "right"]}><View style={styles.header}><Pressable onPress={() => router.back()} hitSlop={12}><MaterialIcons name="arrow-back-ios" size={20} color={colors.foreground}/></Pressable><Text style={[styles.title, { color: colors.foreground }]}>Appeal history</Text></View><ScrollView contentContainerStyle={styles.content}>{appeals.isLoading ? <ActivityIndicator color={colors.primary}/> : appeals.data?.length ? appeals.data.map((appeal) => <View key={appeal.id} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.top}><MaterialIcons name={appeal.status === "approved" ? "check-circle" : appeal.status === "rejected" ? "cancel" : "pending"} size={23} color={appeal.status === "approved" ? colors.success : appeal.status === "rejected" ? colors.error : colors.warning}/><Text style={[styles.status, { color: colors.foreground }]}>{appeal.status}</Text><Text style={[styles.date, { color: colors.muted }]}>{new Date(appeal.createdAt).toLocaleDateString()}</Text></View><Text style={[styles.reason, { color: colors.muted }]}>{appeal.reason}</Text>{appeal.reviewNote ? <Text style={[styles.note, { color: colors.foreground }]}>Admin note: {appeal.reviewNote}</Text> : null}</View>) : <View style={styles.empty}><MaterialIcons name="history" size={42} color={colors.muted}/><Text style={[styles.emptyTitle, { color: colors.foreground }]}>No appeals yet</Text><Text style={[styles.emptyText, { color: colors.muted }]}>Submitted account reviews will appear here.</Text></View>}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 16, padding: 20 }, title: { flex: 1, fontSize: 21, fontWeight: "800" }, content: { padding: 20, paddingBottom: 40 }, card: { borderWidth: 1, borderRadius: 17, padding: 15, marginBottom: 10 }, top: { flexDirection: "row", alignItems: "center", gap: 9 }, status: { fontSize: 14, fontWeight: "800", textTransform: "capitalize" }, date: { marginLeft: "auto", fontSize: 11 }, reason: { fontSize: 13, lineHeight: 19, marginTop: 12 }, note: { fontSize: 12, lineHeight: 18, marginTop: 10 }, empty: { alignItems: "center", paddingTop: 70 }, emptyTitle: { fontSize: 18, fontWeight: "800", marginTop: 15 }, emptyText: { fontSize: 13, marginTop: 6 } });
