import { useState } from "react";
import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

export default function NewGroupScreen() { const colors = useColors(); const router = useRouter(); const [name, setName] = useState(""); const [invite, setInvite] = useState(false); return <ScreenContainer className="bg-background" edges={["top", "bottom", "left", "right"]}><View style={styles.header}><Pressable onPress={() => router.back()}><MaterialIcons name="close" size={23} color={colors.foreground}/></Pressable><Text style={[styles.title, { color: colors.foreground }]}>New group</Text><Pressable onPress={() => router.back()}><Text style={[styles.create, { color: name.trim() ? colors.primary : colors.muted }]}>Create</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}><View style={[styles.groupAvatar, { backgroundColor: colors.primary }]}><MaterialIcons name="photo-camera" size={28} color="#fff"/></View><TextInput value={name} onChangeText={setName} placeholder="Group name" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground, borderBottomColor: colors.border }]} /><Text style={[styles.section, { color: colors.muted }]}>MEMBERS</Text><View style={[styles.empty, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialIcons name="person-add-alt-1" size={24} color={colors.primary}/><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Add people by phone number</Text><Text style={[styles.emptyText, { color: colors.muted }]}>You can create a group alone and add members later, or share an invite link.</Text><Pressable onPress={() => setInvite(!invite)} style={[styles.link, { borderColor: colors.primary }]}><MaterialIcons name="link" size={18} color={colors.primary}/><Text style={[styles.linkText, { color: colors.primary }]}>{invite ? "Invite link copied" : "Create invite link"}</Text></Pressable></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 16, padding: 20 }, title: { flex: 1, fontSize: 21, fontWeight: "800" }, create: { fontSize: 14, fontWeight: "800" }, content: { padding: 24 }, groupAvatar: { width: 84, height: 84, borderRadius: 42, alignSelf: "center", alignItems: "center", justifyContent: "center", marginBottom: 28 }, input: { height: 52, borderBottomWidth: 1, fontSize: 18, textAlign: "center" }, section: { fontSize: 11, fontWeight: "800", letterSpacing: 1.2, marginTop: 32, marginBottom: 10 }, empty: { borderWidth: 1, borderRadius: 20, alignItems: "center", padding: 24 }, emptyTitle: { fontSize: 15, fontWeight: "800", marginTop: 12 }, emptyText: { fontSize: 13, lineHeight: 19, textAlign: "center", marginTop: 7 }, link: { flexDirection: "row", alignItems: "center", gap: 8, borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 11, marginTop: 20 }, linkText: { fontSize: 13, fontWeight: "800" } });
