import { useState } from "react";
import { useRouter } from "expo-router";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

export default function ProfileScreen() {
  const colors = useColors(); const router = useRouter(); const [name, setName] = useState("Alex Morgan"); const [about, setAbout] = useState("Available");
  return <ScreenContainer className="bg-background" edges={["top", "bottom", "left", "right"]}><View style={styles.header}><Pressable onPress={() => router.back()}><MaterialIcons name="arrow-back-ios" size={20} color={colors.foreground}/></Pressable><Text style={[styles.title, { color: colors.foreground }]}>Profile</Text><Pressable onPress={() => router.back()}><Text style={[styles.save, { color: colors.primary }]}>Save</Text></Pressable></View><View style={styles.content}><View style={[styles.avatar, { backgroundColor: colors.primary }]}><Text style={styles.initials}>AM</Text><View style={styles.camera}><MaterialIcons name="photo-camera" size={15} color="#fff"/></View></View><Text style={[styles.label, { color: colors.muted }]}>NAME</Text><TextInput value={name} onChangeText={setName} style={[styles.input, { color: colors.foreground, borderBottomColor: colors.border }]} /><Text style={[styles.label, { color: colors.muted }]}>ABOUT</Text><TextInput value={about} onChangeText={setAbout} style={[styles.input, { color: colors.foreground, borderBottomColor: colors.border }]} /><View style={[styles.private, { backgroundColor: colors.surface }]}><MaterialIcons name="lock" size={18} color={colors.success}/><Text style={[styles.privateText, { color: colors.muted }]}>Your email and phone are private. Only your name, photo, and about line are visible to contacts.</Text></View></View></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 16, padding: 20 }, title: { flex: 1, fontSize: 21, fontWeight: "800" }, save: { fontSize: 14, fontWeight: "800" }, content: { padding: 24, alignItems: "stretch" }, avatar: { width: 96, height: 96, borderRadius: 48, alignSelf: "center", alignItems: "center", justifyContent: "center", marginBottom: 30 }, initials: { color: "#fff", fontSize: 30, fontWeight: "800" }, camera: { position: "absolute", bottom: 0, right: 0, width: 30, height: 30, borderRadius: 15, backgroundColor: "#0EA5E9", alignItems: "center", justifyContent: "center" }, label: { fontSize: 11, letterSpacing: 1.2, fontWeight: "800", marginTop: 18 }, input: { height: 48, borderBottomWidth: 1, fontSize: 16 }, private: { flexDirection: "row", gap: 10, padding: 14, borderRadius: 15, marginTop: 28 }, privateText: { flex: 1, fontSize: 12, lineHeight: 17 } });
