import { useMemo, useState } from "react";
import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

const results = [{ chat: "Maya Chen", text: "The new collection looks incredible.", time: "9:42 AM" }, { chat: "Design Circle", text: "I’ll share the prototype at 3.", time: "8:17 AM" }, { chat: "Weekend plans", text: "Brunch at 11 works for me", time: "Yesterday" }];
export default function SearchScreen() { const colors = useColors(); const router = useRouter(); const [query, setQuery] = useState(""); const visible = useMemo(() => results.filter((item) => !query.trim() || `${item.chat} ${item.text}`.toLowerCase().includes(query.toLowerCase())), [query]); return <ScreenContainer className="bg-background" edges={["top", "bottom", "left", "right"]}><View style={styles.header}><Pressable onPress={() => router.back()}><MaterialIcons name="arrow-back-ios" size={20} color={colors.foreground}/></Pressable><Text style={[styles.title, { color: colors.foreground }]}>Search messages</Text></View><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialIcons name="search" size={20} color={colors.muted}/><TextInput autoFocus value={query} onChangeText={setQuery} placeholder="Search across chats" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground }]}/></View><ScrollView contentContainerStyle={styles.content}>{visible.map((item) => <Pressable key={item.text} style={[styles.result, { borderBottomColor: colors.border }]} onPress={() => router.back()}><MaterialIcons name="chat-bubble-outline" size={19} color={colors.primary}/><View style={styles.copy}><View style={styles.top}><Text style={[styles.chat, { color: colors.foreground }]}>{item.chat}</Text><Text style={[styles.time, { color: colors.muted }]}>{item.time}</Text></View><Text style={[styles.message, { color: colors.muted }]}>{item.text}</Text></View></Pressable>)}{visible.length === 0 ? <Text style={[styles.empty, { color: colors.muted }]}>No messages found.</Text> : null}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 16, padding: 20 }, title: { flex: 1, fontSize: 21, fontWeight: "800" }, search: { height: 50, borderRadius: 16, borderWidth: 1, marginHorizontal: 20, paddingHorizontal: 14, flexDirection: "row", alignItems: "center" }, input: { flex: 1, marginLeft: 8, fontSize: 15 }, content: { padding: 20 }, result: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 15, borderBottomWidth: StyleSheet.hairlineWidth }, copy: { flex: 1 }, top: { flexDirection: "row", justifyContent: "space-between" }, chat: { fontSize: 14, fontWeight: "800" }, time: { fontSize: 11 }, message: { fontSize: 13, marginTop: 5 }, empty: { textAlign: "center", marginTop: 50 } });
