import { WebPushRow } from "@/components/web-push-row";
import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

const descriptions: Record<string, string> = { privacy: "Control who can reach you and how your activity appears.", notifications: "Choose which messages, groups, and calls can notify you.", storage: "Review media usage, downloads, and network preferences.", blocked: "People you block cannot message or call you on Varnox.", account: "Manage your profile, security, and account details.", search: "Search your conversations and saved messages." };

type SettingKey = "readReceipts" | "lastSeen" | "darkTheme" | "notificationsMessages" | "notificationsGroups" | "notificationsCalls";

export default function SettingDetailScreen() {
  const colors = useColors(); const router = useRouter(); const params = useLocalSearchParams<{ title?: string; section?: string; subtitle?: string }>();
  const title = String(params.title ?? "Settings"); const section = String(params.section ?? "settings"); const subtitle = String(params.subtitle ?? descriptions[section] ?? "Manage this Varnox setting.");
  const settingsQuery = trpc.settings.get.useQuery(undefined, { enabled: section !== "blocked" }); const saveSettings = trpc.settings.update.useMutation({ onSuccess: () => settingsQuery.refetch() });
  const blocksQuery = trpc.blocks.list.useQuery(undefined, { enabled: section === "blocked" }); const block = trpc.blocks.block.useMutation({ onSuccess: () => { blocksQuery.refetch(); setSearch(""); } }); const unblock = trpc.blocks.unblock.useMutation({ onSuccess: () => blocksQuery.refetch() });
  const [values, setValues] = useState<Record<SettingKey, boolean>>({ readReceipts: true, lastSeen: true, darkTheme: false, notificationsMessages: true, notificationsGroups: true, notificationsCalls: true });
  const [search, setSearch] = useState(""); const peopleQuery = trpc.people.search.useQuery({ query: search.trim() }, { enabled: section === "blocked" && search.trim().length >= 2 });
  useEffect(() => { const data = settingsQuery.data; if (!data) return; setValues({ readReceipts: Boolean(data.readReceipts), lastSeen: Boolean(data.lastSeen), darkTheme: Boolean(data.darkTheme), notificationsMessages: Boolean(data.notificationsMessages), notificationsGroups: Boolean(data.notificationsGroups), notificationsCalls: Boolean(data.notificationsCalls) }); }, [settingsQuery.data]);
  const toggle = (key: SettingKey, value: boolean) => { setValues((current) => ({ ...current, [key]: value })); saveSettings.mutate({ [key]: value }); };
  const notificationRows: Array<{ key: SettingKey; title: string; subtitle: string; icon: React.ComponentProps<typeof MaterialIcons>["name"] }> = [{ key: "notificationsMessages", title: "Message notifications", subtitle: "Direct messages and replies", icon: "chat-bubble-outline" }, { key: "notificationsGroups", title: "Group notifications", subtitle: "New messages in groups", icon: "groups" }, { key: "notificationsCalls", title: "Call notifications", subtitle: "Incoming voice and video calls", icon: "call" }];
  return <ScreenContainer className="bg-background" edges={["top", "bottom", "left", "right"]}><View style={styles.header}><Pressable onPress={() => router.back()} hitSlop={12}><MaterialIcons name="arrow-back-ios" size={20} color={colors.foreground}/></Pressable><Text style={[styles.title, { color: colors.foreground }]}>{title}</Text></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator>{section === "blocked" ? <BlockedContent colors={colors} search={search} setSearch={setSearch} blocks={blocksQuery.data ?? []} results={peopleQuery.data ?? []} onBlock={(userId) => block.mutate({ userId })} onUnblock={(userId) => unblock.mutate({ userId })}/> : <><View style={[styles.hero, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.heroIcon, { backgroundColor: "rgba(0,168,132,.14)" }]}><MaterialIcons name={section === "privacy" ? "lock-outline" : section === "notifications" ? "notifications-none" : "tune"} size={25} color={colors.primary}/></View><Text style={[styles.heroTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.subtitle, { color: colors.muted }]}>{subtitle}</Text></View><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{section === "notifications" ? <>{notificationRows.map((row) => <DetailRow key={row.key} icon={row.icon} title={row.title} subtitle={row.subtitle} value={values[row.key]} onChange={(value) => toggle(row.key, value)} colors={colors}/>)}<WebPushRow colors={colors}/></> : <><DetailRow icon="lock-outline" title="Private by default" subtitle="Keep your account details protected" value={values.readReceipts} onChange={(value) => toggle("readReceipts", value)} colors={colors}/><DetailRow icon="visibility" title="Last seen and online" subtitle="Control who can see your activity" value={values.lastSeen} onChange={(value) => toggle("lastSeen", value)} colors={colors}/></> }</View><Pressable onPress={() => {}} style={[styles.action, { borderColor: colors.border }]}><MaterialIcons name={section === "storage" ? "delete-sweep" : "help-outline"} size={20} color={section === "storage" ? colors.error : colors.primary}/><Text style={[styles.actionText, { color: section === "storage" ? colors.error : colors.primary }]}>{section === "storage" ? "Clear downloaded media" : "Learn more about this setting"}</Text></Pressable></>}</ScrollView></ScreenContainer>;
}

function BlockedContent({ colors, search, setSearch, blocks, results, onBlock, onUnblock }: { colors: ReturnType<typeof useColors>; search: string; setSearch: (value: string) => void; blocks: Array<{ id: number; name: string | null; username: string | null; email: string | null }>; results: Array<{ id: number; name: string | null; email: string | null }>; onBlock: (userId: number) => void; onUnblock: (userId: number) => void }) { return <><View style={[styles.hero, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.heroIcon, { backgroundColor: "rgba(239,68,68,.13)" }]}><MaterialIcons name="block" size={25} color={colors.error}/></View><Text style={[styles.heroTitle, { color: colors.foreground }]}>Blocked contacts</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Blocked people cannot message or call you.</Text></View><TextInput value={search} onChangeText={setSearch} placeholder="Search people to block" placeholderTextColor={colors.muted} style={[styles.searchInput, { color: colors.foreground, backgroundColor: colors.surface, borderColor: colors.border }]}/>{results.map((person) => <Pressable key={person.id} onPress={() => onBlock(person.id)} style={[styles.personRow, { borderBottomColor: colors.border }]}><MaterialIcons name="person-add" size={21} color={colors.primary}/><Text style={[styles.personText, { color: colors.foreground }]}>{person.name ?? person.email ?? "Varnox user"}</Text><Text style={[styles.actionText, { color: colors.primary }]}>Block</Text></Pressable>)}<Text style={[styles.sectionLabel, { color: colors.muted }]}>CURRENTLY BLOCKED</Text>{blocks.length === 0 ? <Text style={[styles.empty, { color: colors.muted }]}>No blocked contacts.</Text> : blocks.map((person) => <View key={person.id} style={[styles.personRow, { borderBottomColor: colors.border }]}><MaterialIcons name="block" size={21} color={colors.error}/><Text style={[styles.personText, { color: colors.foreground }]}>{person.name ?? person.username ?? person.email ?? "Varnox user"}</Text><Pressable onPress={() => onUnblock(person.id)}><Text style={[styles.actionText, { color: colors.primary }]}>Unblock</Text></Pressable></View>)}</>; }
function DetailRow({ icon, title, subtitle, value, onChange, colors }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; title: string; subtitle: string; value: boolean; onChange: (value: boolean) => void; colors: ReturnType<typeof useColors> }) { return <Pressable onPress={() => onChange(!value)} style={({ pressed }) => [styles.row, { borderBottomColor: colors.border }, pressed && { opacity: 0.65 }]}><View style={[styles.rowIcon, { backgroundColor: "rgba(0,168,132,.14)" }]}><MaterialIcons name={icon} size={20} color={colors.primary}/></View><View style={styles.copy}><Text style={[styles.rowTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.rowSubtitle, { color: colors.muted }]}>{subtitle}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{ false: colors.border, true: "#A7E8CD" }} thumbColor={value ? colors.success : "#fff"}/></Pressable>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 16, padding: 20 }, title: { flex: 1, fontSize: 21, fontWeight: "800" }, content: { padding: 20, paddingBottom: 40 }, hero: { borderWidth: 1, borderRadius: 20, padding: 20, marginBottom: 14 }, heroIcon: { width: 48, height: 48, borderRadius: 15, alignItems: "center", justifyContent: "center", marginBottom: 16 }, heroTitle: { fontSize: 22, fontWeight: "800" }, subtitle: { fontSize: 14, lineHeight: 21, marginTop: 7 }, card: { borderWidth: 1, borderRadius: 20, paddingHorizontal: 16 }, row: { minHeight: 80, flexDirection: "row", alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth }, rowIcon: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, paddingHorizontal: 12 }, rowTitle: { fontSize: 14, fontWeight: "800" }, rowSubtitle: { fontSize: 12, lineHeight: 17, marginTop: 4 }, action: { flexDirection: "row", alignItems: "center", gap: 10, borderWidth: 1, borderRadius: 16, minHeight: 52, paddingHorizontal: 16, marginTop: 14 }, actionText: { fontSize: 13, fontWeight: "800" }, searchInput: { height: 50, borderWidth: 1, borderRadius: 15, paddingHorizontal: 15, fontSize: 15, marginBottom: 12 }, personRow: { minHeight: 58, flexDirection: "row", alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth, gap: 10 }, personText: { flex: 1, fontSize: 14, fontWeight: "700" }, sectionLabel: { fontSize: 11, fontWeight: "800", letterSpacing: 1.2, marginTop: 24, marginBottom: 8 }, empty: { fontSize: 13, paddingVertical: 14 } });
