import { useState } from "react";
import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

export default function ChatSettingsScreen() {
  const colors = useColors(); const router = useRouter(); const [receipts, setReceipts] = useState(true); const [disappearing, setDisappearing] = useState(false);
  const row = (icon: React.ComponentProps<typeof MaterialIcons>["name"], title: string, subtitle: string, control?: React.ReactNode) => <View style={[styles.row, { borderBottomColor: colors.border }]}><View style={[styles.icon, { backgroundColor: "rgba(245,158,11,.13)" }]}><MaterialIcons name={icon} size={20} color={colors.primary}/></View><View style={styles.copy}><Text style={[styles.rowTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.sub, { color: colors.muted }]}>{subtitle}</Text></View>{control ?? <MaterialIcons name="chevron-right" size={20} color={colors.muted}/>}</View>;
  return <ScreenContainer className="bg-background" edges={["top", "bottom", "left", "right"]}><View style={styles.header}><Pressable onPress={() => router.back()}><MaterialIcons name="arrow-back-ios" size={20} color={colors.foreground}/></Pressable><Text style={[styles.title, { color: colors.foreground }]}>Chat settings</Text></View><ScrollView contentContainerStyle={styles.content}><View style={[styles.hero, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.heroTitle, { color: colors.foreground }]}>Varnox conversations</Text><Text style={[styles.sub, { color: colors.muted }]}>Control how chats look, behave, and keep your media.</Text></View><View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}>{row("palette", "Theme and wallpaper", "Choose light, dark, or one of five wallpapers")}{row("timer", "Disappearing messages", "24 hours, 7 days, or 90 days", <Switch value={disappearing} onValueChange={setDisappearing} trackColor={{ false: colors.border, true: "#A7E8CD" }} thumbColor={disappearing ? colors.success : "#fff"}/>)}{row("done-all", "Read receipts", "Show when messages are read", <Switch value={receipts} onValueChange={setReceipts} trackColor={{ false: colors.border, true: "#A7E8CD" }} thumbColor={receipts ? colors.success : "#fff"}/>)}{row("photo-library", "Media visibility", "Photos and videos in your gallery")}{row("download", "Export chat", "Save a copy of this conversation")}</View></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 16, padding: 20 }, title: { flex: 1, fontSize: 21, fontWeight: "800" }, content: { padding: 20 }, hero: { borderWidth: 1, borderRadius: 20, padding: 18, marginBottom: 14 }, heroTitle: { fontSize: 18, fontWeight: "800", marginBottom: 5 }, card: { borderWidth: 1, borderRadius: 20, paddingHorizontal: 14 }, row: { minHeight: 76, flexDirection: "row", alignItems: "center", borderBottomWidth: StyleSheet.hairlineWidth }, icon: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, marginLeft: 12 }, rowTitle: { fontSize: 14, fontWeight: "800" }, sub: { fontSize: 12, lineHeight: 17, marginTop: 4 } });
