import { useState } from "react";
import { useRouter } from "expo-router";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

type SupportMessage = { id: string; text: string; mine?: boolean };
const welcome: SupportMessage[] = [{ id: "welcome", text: "I’m Varnox Support. I can help with login, groups, privacy, blocking, reports, calls, and media. What do you need?" }];

export default function SupportScreen() {
  const colors = useColors(); const router = useRouter(); const [text, setText] = useState(""); const [messages, setMessages] = useState(welcome); const ask = trpc.support.ask.useMutation();
  const send = async (value = text) => { const message = value.trim(); if (!message || ask.isPending) return; setText(""); setMessages((current) => [...current, { id: `u-${Date.now()}`, text: message, mine: true }]); try { const answer = await ask.mutateAsync({ message }); setMessages((current) => [...current, { id: `b-${Date.now()}`, text: answer.text }]); } catch { setMessages((current) => [...current, { id: `b-${Date.now()}`, text: "Support is temporarily offline. Please try again shortly." }]); } };
  return <ScreenContainer className="bg-background" edges={["top", "bottom", "left", "right"]}><View style={[styles.header, { borderBottomColor: colors.border }]}><Pressable onPress={() => router.back()}><MaterialIcons name="arrow-back-ios" size={20} color={colors.foreground}/></Pressable><View style={[styles.botAvatar, { backgroundColor: colors.primary }]}><MaterialIcons name="support-agent" size={20} color="#fff"/></View><View style={styles.headerCopy}><Text style={[styles.title, { color: colors.foreground }]}>Varnox Support</Text><Text style={[styles.online, { color: colors.success }]}>Always here to help</Text></View></View><FlatList data={messages} keyExtractor={(item) => item.id} contentContainerStyle={styles.messages} renderItem={({ item }) => <View style={[styles.message, item.mine ? styles.mine : styles.theirs, { backgroundColor: item.mine ? colors.primary : colors.surface, borderColor: colors.border }]}><Text style={[styles.messageText, { color: item.mine ? "#fff" : colors.foreground }]}>{item.text}</Text></View>} ListHeaderComponent={<View style={styles.topicRow}>{["Login help", "Privacy", "Groups", "Report an account"].map((topic) => <Pressable key={topic} onPress={() => void send(topic)} style={[styles.topic, { borderColor: colors.border, backgroundColor: colors.surface }]}><Text style={[styles.topicText, { color: colors.foreground }]}>{topic}</Text></Pressable>)}</View>} /><View style={[styles.composerArea, { borderTopColor: colors.border }]}><View style={[styles.composer, { backgroundColor: colors.surface, borderColor: colors.border }]}><TextInput value={text} onChangeText={setText} placeholder="Ask Varnox Support" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground }]} onSubmitEditing={() => void send()} returnKeyType="send" /></View><Pressable onPress={() => void send()} style={[styles.send, { backgroundColor: colors.primary }]}>{ask.isPending ? <ActivityIndicator color="#fff"/> : <MaterialIcons name="send" size={19} color="#fff"/>}</Pressable></View></ScreenContainer>;
}
const styles = StyleSheet.create({ header: { flexDirection: "row", alignItems: "center", gap: 12, padding: 16, borderBottomWidth: StyleSheet.hairlineWidth }, botAvatar: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center" }, headerCopy: { flex: 1 }, title: { fontSize: 16, fontWeight: "800" }, online: { fontSize: 11, marginTop: 3, fontWeight: "700" }, messages: { padding: 16, gap: 9, flexGrow: 1, justifyContent: "flex-end" }, message: { maxWidth: "82%", paddingHorizontal: 13, paddingVertical: 10, borderRadius: 16, borderWidth: 1 }, mine: { alignSelf: "flex-end", borderBottomRightRadius: 5 }, theirs: { alignSelf: "flex-start", borderBottomLeftRadius: 5 }, messageText: { fontSize: 14, lineHeight: 20 }, topicRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 16 }, topic: { paddingHorizontal: 11, paddingVertical: 8, borderRadius: 15, borderWidth: 1 }, topicText: { fontSize: 12, fontWeight: "700" }, composerArea: { flexDirection: "row", gap: 8, padding: 12, borderTopWidth: StyleSheet.hairlineWidth }, composer: { flex: 1, minHeight: 46, borderWidth: 1, borderRadius: 23, justifyContent: "center" }, input: { paddingHorizontal: 16, fontSize: 15 }, send: { width: 46, height: 46, borderRadius: 23, alignItems: "center", justifyContent: "center" } });
