import type { Express, Request, Response } from "express";
import { createHash, randomBytes, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";
import { COOKIE_NAME, ONE_YEAR_MS } from "../../shared/const.js";
import { getSessionCookieOptions } from "./cookies";
import { sdk } from "./sdk";
import { ENV } from "./env";
import { consumeAuthToken, createAuthToken, getUserByEmail, getUserByUsername, markEmailVerified, updatePasswordHash, upsertUser } from "../db";

const scrypt = promisify(scryptCallback);
const USERNAME_RE = /^[a-zA-Z0-9_]{3,32}$/;

export function normalizeUsername(value: unknown) { const username = String(value ?? "").trim().toLowerCase(); if (!USERNAME_RE.test(username)) throw new Error("Username must be 3–32 characters using letters, numbers, or underscores"); return username; }
export function validatePassword(value: unknown) { const password = String(value ?? ""); if (password.length < 8 || password.length > 128) throw new Error("Password must be 8–128 characters"); return password; }
export async function hashPassword(password: string) { const salt = randomBytes(16).toString("hex"); const derived = await scrypt(password, salt, 64) as Buffer; return `${salt}:${derived.toString("hex")}`; }
async function verifyPassword(password: string, stored: string) { const [salt, hex] = stored.split(":"); if (!salt || !hex) return false; const expected = Buffer.from(hex, "hex"); const actual = await scrypt(password, salt, expected.length) as Buffer; return expected.length === actual.length && timingSafeEqual(expected, actual); }
function hashToken(token: string) { return createHash("sha256").update(token).digest("hex"); }

async function sendEmail(to: string, subject: string, code: string, label: string) {
  if (!ENV.resendApiKey || !ENV.resendFrom) { if (ENV.isProduction) throw new Error("Email delivery is not configured on this server"); console.log(`[EmailAuth] Development ${label} code for ${to}: ${code}`); return false; }
  const response = await fetch("https://api.resend.com/emails", { method: "POST", headers: { Authorization: `Bearer ${ENV.resendApiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ from: ENV.resendFrom, to: [to], subject, text: `Your Varnox ${label} code is ${code}. It expires in 30 minutes.` }) });
  if (!response.ok) throw new Error("The email provider rejected the message"); return true;
}
function userResponse(user: any) { return { id: user.id, openId: user.openId, username: user.username, name: user.name, email: user.email, emailVerifiedAt: user.emailVerifiedAt?.toISOString() ?? null, loginMethod: user.loginMethod, role: user.role, moderationStatus: user.moderationStatus, suspendedUntil: user.suspendedUntil?.toISOString() ?? null, moderationReason: user.moderationReason, lastSignedIn: (user.lastSignedIn ?? new Date()).toISOString() }; }
function setSession(res: Response, req: Request, sessionToken: string) { res.cookie(COOKIE_NAME, sessionToken, { ...getSessionCookieOptions(req), maxAge: ONE_YEAR_MS }); }
function rejectModerated(user: any) { if (user.moderationStatus === "banned") throw new Error(`This Varnox account is banned${user.moderationReason ? `: ${user.moderationReason}` : "."}`); if (user.moderationStatus === "suspended" && (!user.suspendedUntil || user.suspendedUntil > new Date())) throw new Error(`This Varnox account is suspended${user.suspendedUntil ? ` until ${user.suspendedUntil.toLocaleString()}` : ""}${user.moderationReason ? `: ${user.moderationReason}` : "."}`); }

export function registerPasswordAuthRoutes(app: Express) {
  app.post("/api/auth/password/register", async (req: Request, res: Response) => { try { const username = normalizeUsername(req.body?.username); const password = validatePassword(req.body?.password); const email = typeof req.body?.email === "string" && req.body.email.trim() ? req.body.email.trim().toLowerCase() : null; const name = typeof req.body?.name === "string" && req.body.name.trim() ? req.body.name.trim().slice(0, 60) : null; const rawPhone = typeof req.body?.phone === "string" ? req.body.phone.replace(/[^\d+]/g, "") : ""; if (rawPhone && !/^\+?\d{7,15}$/.test(rawPhone)) throw new Error("Enter a valid phone number, for example +254712345678"); const phone = rawPhone || null; if (await getUserByUsername(username)) throw new Error("That username is already taken"); const openId = `password:${username}`; await upsertUser({ openId, username, passwordHash: await hashPassword(password), name: name ?? username, phone, email, loginMethod: "password", lastSignedIn: new Date() }); const user = await getUserByUsername(username); if (!user) throw new Error("Account storage is not available yet"); const sessionToken = await sdk.createSessionToken(openId, { name: name ?? username, expiresInMs: ONE_YEAR_MS }); setSession(res, req, sessionToken); let verificationSent = false; let devCode: string | undefined; if (email) { try { const code = String(Math.floor(100000 + Math.random() * 900000)); await createAuthToken(user.id, "email-verify", hashToken(code), new Date(Date.now() + 30 * 60 * 1000)); verificationSent = await sendEmail(email, "Verify your Varnox email", code, "email verification"); if (!verificationSent) devCode = code; } catch (emailError) { console.log("[Auth] verification email could not be sent:", emailError); verificationSent = false; } } res.json({ app_session_id: sessionToken, user: userResponse(user), verificationSent, devCode }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : "Could not create account" }); } });
  app.post("/api/auth/password/login", async (req: Request, res: Response) => { try { const username = normalizeUsername(req.body?.username); const password = validatePassword(req.body?.password); const user = await getUserByUsername(username); if (!user?.passwordHash || !(await verifyPassword(password, user.passwordHash))) throw new Error("Username or password is incorrect"); rejectModerated(user); await upsertUser({ openId: user.openId, lastSignedIn: new Date() }); const sessionToken = await sdk.createSessionToken(user.openId, { name: user.name ?? username, expiresInMs: ONE_YEAR_MS }); setSession(res, req, sessionToken); res.json({ app_session_id: sessionToken, user: userResponse(user) }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : "Could not sign in" }); } });
  app.post("/api/auth/password/reset/start", async (req: Request, res: Response) => { try { const email = String(req.body?.email ?? "").trim().toLowerCase(); const user = await getUserByEmail(email); const response: { message: string; devCode?: string } = { message: "If an account uses that email, a reset code has been sent." }; if (user?.email) { const code = String(Math.floor(100000 + Math.random() * 900000)); await createAuthToken(user.id, "password-reset", hashToken(code), new Date(Date.now() + 30 * 60 * 1000)); const delivered = await sendEmail(user.email, "Reset your Varnox password", code, "password reset"); if (!delivered) response.devCode = code; } res.json(response); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : "Could not start password reset" }); } });
  app.post("/api/auth/password/reset/complete", async (req: Request, res: Response) => { try { const record = await consumeAuthToken("password-reset", hashToken(String(req.body?.code ?? ""))); const password = validatePassword(req.body?.password); if (!record) throw new Error("The reset code is invalid or expired"); await updatePasswordHash(record.userId, await hashPassword(password)); res.json({ success: true }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : "Could not reset password" }); } });
  app.post("/api/auth/email/verify/start", async (req: Request, res: Response) => { try { const username = normalizeUsername(req.body?.username); const user = await getUserByUsername(username); if (!user?.email) throw new Error("Add an email address to verify this account"); const code = String(Math.floor(100000 + Math.random() * 900000)); await createAuthToken(user.id, "email-verify", hashToken(code), new Date(Date.now() + 30 * 60 * 1000)); const delivered = await sendEmail(user.email, "Verify your Varnox email", code, "email verification"); res.json({ message: "Verification code sent", devCode: delivered ? undefined : code }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : "Could not send verification code" }); } });
  app.post("/api/auth/email/verify/complete", async (req: Request, res: Response) => { try { const record = await consumeAuthToken("email-verify", hashToken(String(req.body?.code ?? ""))); if (!record) throw new Error("The verification code is invalid or expired"); await markEmailVerified(record.userId); res.json({ success: true }); } catch (error) { res.status(400).json({ error: error instanceof Error ? error.message : "Could not verify email" }); } });
}
