import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import * as Auth from "@/lib/_core/auth";
import { trpc } from "@/lib/trpc";

export default function AccountStatusScreen() {
  const router = useRouter(); const params = useLocalSearchParams<{ status?: string; reason?: string; until?: string; username?: string }>();
  const { status = "banned", reason = "Community safety review", until, username = "" } = params; const suspended = status === "suspended"; const dateText = until ? String(until) : "18 September 2026";
  const [appealReason, setAppealReason] = useState(String(reason)); const [usernameInput, setUsernameInput] = useState(String(username));
  const appeal = trpc.appeals.submit.useMutation(); const submitted = appeal.isSuccess;
  const signOut = async () => { await Auth.removeSessionToken(); await Auth.clearUserInfo(); router.replace("/login"); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#0f0f11]"><View style={styles.page}><View style={styles.panel}><View style={styles.brand}><View style={styles.logo}><Text style={styles.logoText}>V</Text><View style={styles.logoDot} /></View></View><View style={styles.alertCard}><View style={styles.alertIcon}><Text style={styles.alertMark}>!</Text></View><Text style={styles.alertTitle}>{suspended ? "This account is temporarily suspended" : "This account can no longer use the Varnox app"}</Text><Text style={styles.alertBody}>Access was withdrawn on {dateText}. Nothing has been deleted: your chats, your messages and your profile are all still here.</Text></View><View style={styles.reasonRow}><Text style={styles.reasonLabel}>Reason given:</Text><Text style={styles.reasonText}>{String(reason)}</Text></View><Text style={styles.explanation}>{suspended ? "You may regain access when the suspension ends. If you think this was a mistake, ask for it to be reviewed." : "If you think this was a mistake, ask for it to be reviewed. Access may be restored after review."}</Text>{!username ? <TextInput value={usernameInput} onChangeText={setUsernameInput} placeholder="Your username" placeholderTextColor="#8f8f96" style={styles.input}/> : null}<TextInput value={appealReason} onChangeText={setAppealReason} placeholder="Tell the admin why this should be reviewed" placeholderTextColor="#8f8f96" multiline style={[styles.input, styles.multiline]}/><Pressable disabled={appeal.isPending || submitted} onPress={() => appeal.mutate({ username: String(username || usernameInput).trim().toLowerCase(), reason: appealReason.trim() })} style={({ pressed }) => [styles.reviewButton, pressed && styles.pressed, (appeal.isPending || submitted) && styles.disabled]}><Text style={styles.reviewText}>{submitted ? "Review requested" : appeal.isPending ? "Sending…" : "Request review"}</Text></Pressable>{appeal.error ? <Text style={styles.error}>{appeal.error.message}</Text> : null}<Pressable onPress={signOut} style={({ pressed }) => [styles.secondaryButton, pressed && styles.pressed]}><Text style={styles.secondaryText}>Sign out</Text></Pressable><Pressable onPress={() => router.replace("/login")} style={({ pressed }) => [styles.secondaryButton, pressed && styles.pressed]}><Text style={styles.secondaryText}>Register a new account</Text></Pressable></View></View></ScreenContainer>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#0f0f11", alignItems: "center", justifyContent: "center", padding: 22 }, panel: { width: "100%", maxWidth: 610, borderWidth: 1, borderColor: "#39393e", borderRadius: 24, padding: 28, backgroundColor: "#101012" }, brand: { marginBottom: 38 }, logo: { width: 92, height: 92, borderRadius: 27, backgroundColor: "#10b981", alignItems: "center", justifyContent: "center", position: "relative" }, logoText: { color: "#f7fffb", fontSize: 58, lineHeight: 64, fontWeight: "900", letterSpacing: -7, marginLeft: -5 }, logoDot: { position: "absolute", right: 16, bottom: 17, width: 17, height: 17, borderRadius: 9, backgroundColor: "#087b65" }, alertCard: { borderWidth: 1, borderColor: "#71333a", borderRadius: 16, backgroundColor: "#35181d", padding: 24, paddingLeft: 70, position: "relative" }, alertIcon: { position: "absolute", left: 23, top: 27, width: 43, height: 43, borderRadius: 22, backgroundColor: "#ff4d5a", alignItems: "center", justifyContent: "center" }, alertMark: { color: "#fff", fontSize: 29, fontWeight: "900" }, alertTitle: { color: "#ff6970", fontSize: 28, lineHeight: 36, fontWeight: "800" }, alertBody: { color: "#f5f1f2", fontSize: 18, lineHeight: 31, marginTop: 20 }, reasonRow: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 18, padding: 19, backgroundColor: "#19191c" }, reasonLabel: { color: "#f3f3f4", fontSize: 17, fontWeight: "800" }, reasonText: { color: "#d1d1d4", fontSize: 17 }, explanation: { color: "#d4d4d8", fontSize: 16, lineHeight: 27, marginTop: 22, marginBottom: 12 }, input: { minHeight: 48, borderWidth: 1, borderColor: "#404045", borderRadius: 13, paddingHorizontal: 14, paddingVertical: 10, color: "#fff", backgroundColor: "#19191c", marginTop: 9, fontSize: 14 }, multiline: { minHeight: 76, textAlignVertical: "top" }, reviewButton: { minHeight: 56, borderWidth: 1, borderColor: "#d8c23a", borderRadius: 30, alignItems: "center", justifyContent: "center", marginTop: 14, marginBottom: 5 }, reviewText: { color: "#f1db3d", fontSize: 18, fontWeight: "800" }, error: { color: "#ff6970", fontSize: 12, marginTop: 8 }, secondaryButton: { minHeight: 56, borderWidth: 1, borderColor: "#404045", borderRadius: 30, alignItems: "center", justifyContent: "center", marginTop: 12 }, secondaryText: { color: "#d4d4d8", fontSize: 17, fontWeight: "600" }, pressed: { opacity: 0.7, transform: [{ scale: 0.99 }] }, disabled: { opacity: 0.55 } });
