import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import * as Api from "@/lib/_core/api";

export default function PasswordResetScreen() { const colors = useColors(); const router = useRouter(); const [email, setEmail] = useState(""); const [code, setCode] = useState(""); const [password, setPassword] = useState(""); const [sent, setSent] = useState(false); const [devCode, setDevCode] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const request = async () => { try { setBusy(true); setError(null); const result = await Api.requestPasswordReset(email.trim()); setSent(true); setDevCode(result.devCode ?? null); setMessage(result.message); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not send reset email"); } finally { setBusy(false); } };
  const complete = async () => { try { setBusy(true); setError(null); await Api.completePasswordReset(code.trim(), password); setMessage("Password changed. You can now log in."); setTimeout(() => router.replace("/login"), 900); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not reset password"); } finally { setBusy(false); } };
  return <ScreenContainer className="bg-background" edges={["top", "bottom", "left", "right"]}><View style={styles.page}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back-ios" size={20} color={colors.foreground}/><Text style={[styles.backText, { color: colors.foreground }]}>Back</Text></Pressable><View style={[styles.icon, { backgroundColor: colors.primary }]}><MaterialIcons name="lock-reset" size={29} color="#fff"/></View><Text style={[styles.title, { color: colors.foreground }]}>Reset your password</Text><Text style={[styles.subtitle, { color: colors.muted }]}>We’ll send a one-time code to the email connected to your Varnox account.</Text>{!sent ? <><TextInput value={email} onChangeText={setEmail} placeholder="you@example.com" placeholderTextColor={colors.muted} keyboardType="email-address" autoCapitalize="none" style={[styles.input, { color: colors.foreground, backgroundColor: colors.surface, borderColor: colors.border }]}/><Button label="Send reset email" onPress={request} busy={busy} colors={colors}/></> : <><Text style={[styles.message, { color: colors.muted }]}>{message}</Text>{devCode ? <Text style={[styles.devCode, { color: colors.primary }]}>Preview code: {devCode}</Text> : null}<TextInput value={code} onChangeText={setCode} placeholder="6-digit code" placeholderTextColor={colors.muted} keyboardType="number-pad" style={[styles.input, { color: colors.foreground, backgroundColor: colors.surface, borderColor: colors.border }]}/><TextInput value={password} onChangeText={setPassword} placeholder="New password (8+ characters)" placeholderTextColor={colors.muted} secureTextEntry style={[styles.input, { color: colors.foreground, backgroundColor: colors.surface, borderColor: colors.border }]}/><Button label="Change password" onPress={complete} busy={busy} colors={colors}/></>}{error ? <Text style={[styles.error, { color: colors.error }]}>{error}</Text> : null}</View></ScreenContainer>; }
function Button({ label, onPress, busy, colors }: { label: string; onPress: () => void; busy: boolean; colors: ReturnType<typeof useColors> }) { return <Pressable disabled={busy} onPress={onPress} style={[styles.button, { backgroundColor: colors.primary }, busy && styles.disabled]}>{busy ? <ActivityIndicator color="#fff"/> : <Text style={styles.buttonText}>{label}</Text>}</Pressable>; }
const styles = StyleSheet.create({ page: { flex: 1, padding: 24, justifyContent: "center" }, back: { flexDirection: "row", alignItems: "center", gap: 8, position: "absolute", top: 22, left: 24 }, backText: { fontSize: 14, fontWeight: "700" }, icon: { width: 62, height: 62, borderRadius: 20, alignItems: "center", justifyContent: "center", marginBottom: 20 }, title: { fontSize: 29, fontWeight: "800" }, subtitle: { fontSize: 15, lineHeight: 22, marginTop: 9, marginBottom: 22 }, input: { height: 52, borderWidth: 1, borderRadius: 15, paddingHorizontal: 15, fontSize: 16, marginTop: 12 }, button: { height: 53, borderRadius: 16, alignItems: "center", justifyContent: "center", marginTop: 18 }, buttonText: { color: "#fff", fontSize: 16, fontWeight: "800" }, message: { fontSize: 13, lineHeight: 19 }, devCode: { fontSize: 14, fontWeight: "800", marginTop: 10 }, error: { fontSize: 13, marginTop: 14 }, disabled: { opacity: 0.6 } });
