import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useAuth } from "@/hooks/use-auth";
import * as Api from "@/lib/_core/api";

export default function VerifyEmailScreen() { const colors = useColors(); const router = useRouter(); const { user, refresh } = useAuth(); const [code, setCode] = useState(""); const [sent, setSent] = useState(false); const [devCode, setDevCode] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const start = async () => { try { setBusy(true); setError(null); const result = await Api.startEmailVerification(user?.username ?? ""); setSent(true); setDevCode(result.devCode ?? null); setMessage(result.message); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not send verification code"); } finally { setBusy(false); } };
  const complete = async () => { try { setBusy(true); setError(null); await Api.completeEmailVerification(code.trim()); await refresh(); setMessage("Email verified successfully."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not verify email"); } finally { setBusy(false); } };
  return <ScreenContainer className="bg-background" edges={["top", "bottom", "left", "right"]}><View style={styles.page}><Pressable onPress={() => router.back()} style={styles.back}><MaterialIcons name="arrow-back-ios" size={20} color={colors.foreground}/><Text style={[styles.backText, { color: colors.foreground }]}>Back</Text></Pressable><View style={[styles.icon, { backgroundColor: colors.primary }]}><MaterialIcons name="verified" size={29} color="#fff"/></View><Text style={[styles.title, { color: colors.foreground }]}>Verify your email</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Verification protects your account and helps you recover it if you forget your password.</Text><View style={[styles.emailCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.emailLabel, { color: colors.muted }]}>EMAIL</Text><Text style={[styles.email, { color: colors.foreground }]}>{user?.email ?? "No email added"}</Text></View>{!sent ? <Button label="Send verification code" onPress={start} busy={busy} colors={colors}/> : <><Text style={[styles.message, { color: colors.muted }]}>{message}</Text>{devCode ? <Text style={[styles.devCode, { color: colors.primary }]}>Preview code: {devCode}</Text> : null}<TextInput value={code} onChangeText={setCode} placeholder="6-digit code" placeholderTextColor={colors.muted} keyboardType="number-pad" style={[styles.input, { color: colors.foreground, backgroundColor: colors.surface, borderColor: colors.border }]}/><Button label="Verify email" onPress={complete} busy={busy} colors={colors}/></>}{error ? <Text style={[styles.error, { color: colors.error }]}>{error}</Text> : null}</View></ScreenContainer>; }
function Button({ label, onPress, busy, colors }: { label: string; onPress: () => void; busy: boolean; colors: ReturnType<typeof useColors> }) { return <Pressable disabled={busy} onPress={onPress} style={[styles.button, { backgroundColor: colors.primary }, busy && styles.disabled]}>{busy ? <ActivityIndicator color="#fff"/> : <Text style={styles.buttonText}>{label}</Text>}</Pressable>; }
const styles = StyleSheet.create({ page: { flex: 1, padding: 24, justifyContent: "center" }, back: { flexDirection: "row", alignItems: "center", gap: 8, position: "absolute", top: 22, left: 24 }, backText: { fontSize: 14, fontWeight: "700" }, icon: { width: 62, height: 62, borderRadius: 20, alignItems: "center", justifyContent: "center", marginBottom: 20 }, title: { fontSize: 29, fontWeight: "800" }, subtitle: { fontSize: 15, lineHeight: 22, marginTop: 9, marginBottom: 22 }, emailCard: { borderWidth: 1, borderRadius: 16, padding: 15 }, emailLabel: { fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, email: { fontSize: 16, fontWeight: "700", marginTop: 7 }, input: { height: 52, borderWidth: 1, borderRadius: 15, paddingHorizontal: 15, fontSize: 16, marginTop: 12 }, button: { height: 53, borderRadius: 16, alignItems: "center", justifyContent: "center", marginTop: 18 }, buttonText: { color: "#fff", fontSize: 16, fontWeight: "800" }, message: { fontSize: 13, lineHeight: 19, marginTop: 18 }, devCode: { fontSize: 14, fontWeight: "800", marginTop: 10 }, error: { fontSize: 13, marginTop: 14 }, disabled: { opacity: 0.6 } });
